services:
  - type: web
    name: harmony-for-hope-1
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: starter
    disk:
      name: auction-data
      mountPath: /data
      sizeGB: 1
